stages:

  supervised_predict:
    matrix: 
      dataset: ${supervised_datasets}
      model: ${supervised_models}
    
    cmd: uv run pg2-benchmark model predict --dataset-manifest ${item.dataset.path} --model-manifest ${item.model.path} --model-dockerfile-folder ${item.model.dockerfile} --model-name ${item.model.name}
    deps:
      - ${item.dataset.path}
      - ${item.model.path}
      - ${item.model.dockerfile}
      - src/pg2_benchmark/cli/model.py
    outs:
      - data/supervised/output/${item.dataset.name}_${item.model.name}.csv

  supervised_metric:
    matrix: 
      dataset: ${supervised_datasets}
      model: ${supervised_models}
    
    cmd: uv run pg2-benchmark metric calc --output-path data/supervised/output/${item.dataset.name}_${item.model.name}.csv --metric-path data/supervised/metric/${item.dataset.name}_${item.model.name}.csv
    deps:
      - data/supervised/output/${item.dataset.name}_${item.model.name}.csv
      - src/pg2_benchmark/cli/metric.py
    outs:
      - data/supervised/metric/${item.dataset.name}_${item.model.name}.csv


  zero_shot_predict:
    matrix: 
      dataset: ${zero_shot_datasets}
      model: ${zero_shot_models}
    
    cmd: uv run pg2-benchmark model predict --dataset-manifest ${item.dataset.path} --model-manifest ${item.model.path} --model-dockerfile-folder ${item.model.dockerfile} --model-name ${item.model.name}
    deps:
      - ${item.dataset.path}
      - ${item.model.path}
      - ${item.model.dockerfile}
      - src/pg2_benchmark/cli/model.py
    outs:
      - data/zero_shot/output/${item.dataset.name}_${item.model.name}.csv

  zero_shot_metric:
    matrix: 
      dataset: ${zero_shot_datasets}
      model: ${zero_shot_models}
    
    cmd: uv run pg2-benchmark metric calc --output-path data/zero_shot/output/${item.dataset.name}_${item.model.name}.csv --metric-path data/zero_shot/metric/${item.dataset.name}_${item.model.name}.csv
    deps:
      - data/zero_shot/output/${item.dataset.name}_${item.model.name}.csv
      - src/pg2_benchmark/cli/metric.py
    outs:
      - data/zero_shot/metric/${item.dataset.name}_${item.model.name}.csv
