supervised_datasets:
  - name: charge_ladder
    path: data/supervised/data/dummy/charge_ladder.toml
  
  - name: neime
    path: data/supervised/data/neime/neime.toml

supervised_models:
  - name: pls
    path: data/supervised/model/pls.toml
    dockerfile: models/pls
    

zero_shot_datasets:
  - name: ranganathan
    path: data/zero_shot/data/ranganathan/ranganathan.toml

zero_shot_models:
  - name: esm
    path: data/zero_shot/model/esm.toml
    dockerfile: models/esm
