supervise_datasets:
  - path: data/supervise/data/neime.toml
    name: neime

supervise_models:
  - path: data/supervise/model/pls.toml
    dockerfile: models/pls
    name: pls

zero_shot_datasets:
  - path: data/zero_shot/data/ranganathan.toml
    name: ranganathan

zero_shot_models:
  - path: data/zero_shot/model/esm.toml
    dockerfile: models/esm
    name: esm
