supervise_datasets:
  - path: data/supervise/data/d1.toml
    name: d1

supervise_models:
  - path: data/supervise/model/m1.toml
    name: m1

zero_shot_datasets:
  - path: data/zero_shot/data/d1.toml
    name: d1

zero_shot_models:
  - path: data/zero_shot/model/m1.toml
    name: m1