supervised_datasets:
  - path: data/supervised/data/neime.toml
    name: neime

supervised_models:
  - path: data/supervised/model/pls.toml
    dockerfile: models/pls
    name: pls

zero_shot_datasets:
  - path: data/zero_shot/data/ranganathan.toml
    name: ranganathan

zero_shot_models:
  - path: data/zero_shot/model/esm.toml
    dockerfile: models/esm
    name: esm
