[project]
name = "pg2-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tintinrevient", email = "zhaobenben007@googlemail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "typer>=0.15.2",
    "loguru>=0.7.3",
    "pg2-dataset",
    "python-on-whales>=0.76.1",
    "gitpython>=3.1.44",
    "pycm>=4.3",
    "streamlit>=1.45.1",
]

[project.scripts]
pg2-benchmark = "pg2_benchmark.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
pg2-dataset = { git = "https://github.com/ProteinGym2/pg2-dataset.git", branch = "main" }

[tool.ruff]
line-length = 88
