aws:
  account_id: ${AWS_ACCOUNT_ID}
  region_name: "us-east-1"
  sagemaker_role_name: "rnd-dev-sagemakerexecutionrole"
  s3_output_prefix: "mango-pe/pg2-benchmark-output"
  s3_training_data_prefix: "mango-pe/pg2-benchmark-training-data"
  instance_type: "ml.m5.xlarge"
  volume_size: 5

output:
  prediction: prediction
  metric: metric

metrics: 
  - spearman
