vars:
  - default.yaml
  - datasets.json
  - models.json

stages:

  setup:
    cmd:
      - mkdir -p logs ${output.prediction} ${output.metric}
      - echo "Created local directories" > logs/setup.txt
    outs:
      - logs/setup.txt

  create_training_job:
    matrix:
      dataset: ${datasets}
      model: ${models}

    cmd:
      - >-
        if [[ ${item.model.input_filename} == /* ]]; then
          echo "Building image from local path: $MODEL"
          docker build \
            -f $(dirname ${item.model.input_filename})/Dockerfile \
            -t ${item.model.name}:latest \
            $(dirname ${item.model.input_filename});
        else
          echo "Pulling image from registry: $MODEL"
          docker pull ${item.model.input_filename} &&
          docker tag ${item.model.input_filename} ${item.model.name}:latest;
        fi
      - >-
        if [[ ${item.model.input_filename} == /* ]]; then
          docker run --rm \
            -v $(realpath ${item.dataset.input_filename}):/$(basename ${item.dataset.input_filename}) \
            -v $(realpath ${item.model.input_filename}):/$(basename ${item.model.input_filename}) \
            -v $(realpath ${output.prediction}):/opt/program/output \
            ${item.model.name}:latest \
            train \
              --dataset-file /$(basename ${item.dataset.input_filename}) \
              --model-card-file /$(basename ${item.model.input_filename});
        else
          docker run --rm \
            -v $(realpath ${item.dataset.input_filename}):/$(basename ${item.dataset.input_filename}) \
            -v $(realpath ${output.prediction}):/opt/program/output \
            ${item.model.name}:latest \
            train \
              --dataset-file /$(basename ${item.dataset.input_filename});
        fi
      - docker image prune -a -f
    deps:
      - logs/setup.txt
      - ${item.dataset.input_filename}
      - ${item.model.input_filename}
    outs:
      - ${output.prediction}/${item.dataset.name}_${item.model.name}.csv:
          cache: true
  
  calculate_metric:
    matrix: 
      dataset: ${datasets}
      model: ${models}

    cmd: >-
      METRICS=$(python -c "import yaml; data = yaml.safe_load(open('default.yaml')); print(' '.join(data['metrics']))") &&
      python $(dvc root)/scripts/metric.py
      --prediction-path ${output.prediction}/${item.dataset.name}_${item.model.name}.csv
      --metric-path ${output.metric}/${item.dataset.name}_${item.model.name}.json
      --selected-metrics $METRICS
    
    deps:
      - ${output.prediction}/${item.dataset.name}_${item.model.name}.csv
    metrics:
      - ${output.metric}/${item.dataset.name}_${item.model.name}.json:
          cache: false
