aws:
  account_id: ${AWS_ACCOUNT_ID}
  region_name: "us-east-1"
  sagemaker_role_name: "rnd-dev-sagemakerexecutionrole "
  s3_output_prefix: "mango-pe/pg2-benchmark-output"
  s3_training_data_prefix: "mango-pe/pg2-benchmark-training-data"
  instance_type: "ml.m5.xlarge"
  volume_size: 5

git:
  git_cache_bust: 1

source:
  datasets_dir: ../../datasets
  models_dir: ../../models
  
destination:
  output_dir: output
  metric_dir: metric