[artifacts]
records = "https://github.com/ProteinGym2/dvc-dataset-registry/protein_gym/A0A1I9GEU1_NEIME_Kennouche_2019.csv"

[records]
sequence_feature = "mutated_sequence"
columns = ["mutated_sequence", "DMS_score"]
schemas = ["pl.String", "pl.Float32"]

[metadata]
name = "PLS regression"

[assays.assay_one]
features = ["mutated_sequence"]
target = "DMS_score"

# TODO: this might be migrated to model.toml into model parameters
[assays.assay_one.constants]
sequence_length = 161
sequence_col_name = "sequence"
target_col_name = "DMS_score"
n_components = 2