vars:
  - type: supervised

  - local:
      git_cache_bust: 1
      datasets_dir: ../datasets
      models_dir: ../models
      output_dir: output/local
      metric_dir: metric/local

  - datasets:
    - name: charge_ladder
      local_path: ../datasets/dummy/charge_ladder.toml
  
    - name: neime
      local_path: ../datasets/neime/neime.toml

  - models:
    - name: pls
      local_path: ../models/pls/pls.toml
      dockerfile: ../models/pls

stages:
  predict:
    matrix: 
      dataset: ${datasets}
      model: ${models}
    
    cmd: uv run pg2-benchmark model predict --type ${type} --dataset-manifest ${item.dataset.local_path} --model-manifest ${item.model.local_path} --model-dockerfile-folder ${item.model.dockerfile} --model-name ${item.model.name}
    deps:
      - ${item.dataset.local_path}
      - ${item.model.local_path}
      - ${item.model.dockerfile}
      - ../src/pg2_benchmark/cli/model.py
    outs:
      - ${local.output_dir}/${item.dataset.name}_${item.model.name}.csv:
          cache: true

  calc_metric:
    matrix: 
      dataset: ${datasets}
      model: ${models}
    
    cmd: uv run pg2-benchmark metric calc --output-path ${local.output_dir}/${item.dataset.name}_${item.model.name}.csv --metric-path ${local.metric_dir}/${item.dataset.name}_${item.model.name}.csv
    deps:
      - ${local.output_dir}/${item.dataset.name}_${item.model.name}.csv
      - ../src/pg2_benchmark/cli/metric.py
    outs:
      - ${local.metric_dir}/${item.dataset.name}_${item.model.name}.csv:
          cache: true